export const ADD_TRANSACTION = 'ADD_TRNSACTION';
export const DELETE_TRANSACTION = 'DELELTE_TRANSACTION';
export const CALCULATE_BALANCE = 'CALCULATE_BALANCE';
export const CALCULATE_INCOME = 'CALCULATE_INCOME';
export const CALCULATE_EXPENSE = 'CALCULATE_EXPENSE';
export const SHOW_FORM   = 'SHOW_FORM';
export const CLOSE_FORM  = 'CLOSE_FORM'